### PR TITLE
'Podspec' file has been added.

### PR DESCRIPTION
**Pull request by maximkhatskevich**
These fixes allow to use this library as a private Pod. If you accept this pull request - please don't forget to update 's.source' property value with URL to your repository.

### CODE REVIEW

**Comment by iMartinKiss** [comment]
The podfile references version 0.2.0, which is from March 2014. Is it possible to reference latest commit on master withou creating tags?

**Comment by maximkhatskevich** [comment]
It doesn't really matter as far as you do not officially publish your repo on CocoaPods.org. Just leave as is, and anyone who wants to use this library as a pod should include this line in Podfile:

pod 'Objective-Chain', :git => 'https://github.com/iMartinKiss/Objective-Chain.git'

This will always fetch latest commit from default branch (usually 'master').

**Comment by iMartinKiss** [comment]
Ok, thanks.

**Comment by maximkhatskevich** [comment]
No problem! Don't forget to change 's.source' property value (see above).

**Comment by iMartinKiss** [comment]
I did :) https://github.com/iMartinKiss/Objective-Chain/blob/master/Objective-Chain.podspec

**Pull request merged**
